DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
  ID INTEGER NOT NULL,
  DOCUMENT_TYPE VARCHAR(10) NOT NULL,
  DOCUMENT_NUMBER VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  FIRST_NAME VARCHAR(100) NOT NULL,
  PHONE_NUMBER VARCHAR(50),
  ADDRESS VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IP_ADDRESS VARCHAR(100) NOT NULL,
  CONSTRAINT PK_PERSON PRIMARY KEY(ID)
);